### ISSUE TITLE
Fix FastGraph, PrimeGraph tests (AttributeError: 'list' object has no attribute 'apex')

### ISSUE THREAD

**Issue by nskeip** [nskeip/calculations#5]
```
======================================================================
ERROR: test_fast_graph (spectrum_tests.calculations.graphs_test.GraphsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nike/src/calculations/src/tests/spectrum_tests/calculations/graphs_test.py", line 34, in test_fast_graph
    g = FastGraph(apex)
  File "/home/nike/src/calculations/src/spectrum/calculations/graphs.py", line 49, in __init__
    apex = group.apex()
AttributeError: 'list' object has no attribute 'apex'

======================================================================
ERROR: test_prime_graph (spectrum_tests.calculations.graphs_test.GraphsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nike/src/calculations/src/tests/spectrum_tests/calculations/graphs_test.py", line 48, in test_prime_graph
    g = PrimeGraph([72, 90, 240, 246, 328, 410, 728, 730])
  File "/home/nike/src/calculations/src/spectrum/calculations/graphs.py", line 34, in __init__
    apex = group.apex()
AttributeError: 'list' object has no attribute 'apex'

----------------------------------------------------------------------
```

**Comment by nskeip** [comment]
Fixed
